apiVersion: v1
kind: PersistentVolume
metadata:
  name: services-pv
  labels:
    app: services-pv
  annotations:
    description: "Este PV é utilizado para persistir os dados do DB e N8N (Mock flow payment order)"
spec:
  capacity:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/docker/posTechFiap
    type: DirectoryOrCreate