apiVersion: v1
kind: Service
metadata:
  name: services-svc-load-balancer
  labels:
    app: services-svc-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: services-deployment
  ports:
    - name: n8n
      protocol: TCP
      port: 80
      targetPort: 5678
      nodePort: 31678
