apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-consumer-billing-deployment
  labels:
    app: adapter-consumer-billing-deployment
  annotations:
    description: "Este pod contem o adapter consumer billing da aplicacao, onde expoe as APIs para que o provedor de pagamento possa atualizar o status do pagamento do pedido"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adapter-consumer-billing-deployment
  template:
    metadata:
      labels:
        app: adapter-consumer-billing-deployment
    spec:
      containers:
        - name: adapter-consumer-billing
          image: micheldossantos/adapter-consumer-billing-fast-food:latest
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            requests:
              cpu: 0.5
            limits:
              cpu: 1
          env:
            - name: PROFILE
              valueFrom:
                secretKeyRef:
                  name: secrets-app
                  key: PROFILE
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: secrets-app
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secrets-app
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-app
                  key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 30