apiVersion: v1
kind: Service
metadata:
  name: adapter-rest-svc-load-balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app: adapter-rest-svc-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: adapter-rest-deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
      nodePort: 31081