apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: services-pvc
  labels:
    app: services-pvc
  annotations:
    description: "Este PVC é utilizado para persistir os dados do DB e N8N (Mock flow payment order)"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi